
version: 2

sources: 
  - name: gz_raw_data
    description: raw_gz_data
    tables: 
    - name: sales
      identifier: raw_gz_sales
      description: raw_gz_sales
      tests:
        - unique:
            column_name: (orders_id || "_" || pdt_id)
        - not_null:
            column_name: (orders_id || "_" || pdt_id)     
    - name: product
      identifier: raw_gz_product
      description: raw_gz_product
      columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null      
    - name: ship
      identifier: raw_gz_ship
      description: raw_gz_ship
      columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null      